# Generated by Django 5.1.1 on 2024-10-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VersoLivro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'imageupload',
            },
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VersoLivro.capa'),
        ),
    ]
