# Generated by Django 5.1.1 on 2024-10-01 18:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VersoLivro', '0002_capa_alter_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='VersoLivro/static/img'), upload_to=''),
        ),
        migrations.DeleteModel(
            name='Capa',
        ),
    ]
