# Generated by Django 5.1.1 on 2024-10-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VersoLivro', '0007_alter_capitulo_titulo_alter_livro_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
