# Generated by Django 5.1.1 on 2024-10-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VersoLivro', '0008_alter_capitulo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='texto',
            field=models.TextField(default='Texto..', max_length=500),
        ),
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(default='Sinopse..', max_length=200),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
