# Generated by Django 5.1.2 on 2024-10-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VersoLivro', '0009_alter_capitulo_texto_alter_livro_sinopse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
